### ISSUE TITLE
java.lang.IllegalArgumentException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:25):1

### ISSUE THREAD

**Issue by bugmailer** [theapache64/lab#15]
<html><head></head><body><div class="msg"> <div style="font-size:16px;border:1px solid #e0e0e0;max-width:800px;font-family:roboto,sans-serif;font-weight:400"> <div style="padding:20px 0px 20px 0px;text-align:center;background-color:#ffffff"><img src="https://i.stack.imgur.com/U2JVG.png" style="width:145px;min-height:40px"></div> <div style="padding:24px 24px 24px 24px;background-color:#F44336;font-family:roboto,sans-serif;font-weight:400"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div style="font-size:14px;line-height:16px;color:#fff">BugMailer Example</div> <div style="font-size:20px;line-height:24px;color:#ffffff">New issue found in com.theah64.bugmailerexample</div> </td> <td> <div style="text-align:right"><img src="https://ci6.googleusercontent.com/proxy/Cvj52vFVxSfNWI4XcQgZJvyDSATy77fAyZvSRAMKVOONvK0uQn8NBMx1LyeaDGUkZ7c8xyQ-UiwGXlRWUvEpiia0Euc3wL-kBn8aWPjlGZmGgxBZpTyJRZgJuD9RVkPun0e9m8odWw=s0-d-e1-ft#https://www.gstatic.com/images/icons/material/system/2x/bug_report_white_24dp.png" style="min-height:24px;width:24px"></div> </td> </tr> </tbody> </table> </div> <div style="font-family:roboto,sans-serif;font-weight:400"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Fatal Error</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div><b><span style='color:#F44336;'>java.lang.IllegalArgumentException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:25)</span></b></div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">App Version Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>1.0</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">App Version Code</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>1</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">File Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>MainActivity.java</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">API Level</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>23</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Time of Occurrence</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>Thu Feb 08 20:53:18 GMT+05:30 2018</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Device</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>generic_x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Model</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>Android SDK built for x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Product</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>sdk_google_phone_x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Exception Message</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>java.lang.IllegalArgumentException: Test exception<br><span style='color:#F44336;'><b>	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:25)<b></span><br>	at android.view.View.performClick(View.java:5198)<br>	at android.view.View$PerformClick.run(View.java:21147)<br>	at android.os.Handler.handleCallback(Handler.java:739)<br>	at android.os.Handler.dispatchMessage(Handler.java:95)<br>	at android.os.Looper.loop(Looper.java:148)<br>	at android.app.ActivityThread.main(ActivityThread.java:5417)<br>	at java.lang.reflect.Method.invoke(Native Method)<br>	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)<br>	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)<br></div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>theapache64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Age</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>20</div> </td> </tr> </tbody> </table> </div> </div><div style="background-color:#ffffff;margin:0px 0px 0px 0px;font-size:14px;font-family:roboto,sans-serif;font-weight:400"> <div style="padding-left:20px;font-size:14px;line-height:16px;padding-top:12px;padding-bottom:34px;padding-top:34px;text-align:right;font-family:roboto,sans-serif;font-weight:500"> <a href="http://google.com/search?q=java.lang.IllegalArgumentException Test exception at .MainActivity$1.onClick(MainActivity.java25)" style="text-decoration:none;margin-right:24px;padding:12px 12px 12px 12px;border:0;color:#F44336;background-color:#ffffff;font-family:roboto,sans-serif;font-weight:500;border-radius:2px" target="_blank" rel="noreferrer" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://console.firebase.google.com/project/anona-705d7/monitoring/app/android:com.cybaze.goodbuy/cluster/7846c195?utm_source%3Dalerts%26utm_medium%3Demail%26utm_campaign%3Dcrash%26utm_content%3Dcluster&amp;source=gmail&amp;ust=1504955366065000&amp;usg=AFQjCNHDa_-uwZO9NB_x2q7mwXfkTP2EYw">SEARCH WITH GOOGLE</a></div> </div> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> </div> <div style="background-color:#343434;padding:23px 24px 23px 24px;min-height:42px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400" cellpadding="0" cellspacing="0"> <tbody> <tr> <td style="text-align:right;padding:0"> <div style="line-height:14px;font-size:10px;color:#fff">BugMailer<br><a style="color:#fff" href="mailto:theapache64@gmail.com"> theapache64@gmail.com </a><br><a style="color:#fff" href="https://github.com/theapache64/BugMailer">A Github opensource project</a><br></div> </td> </tr> </tbody> </table> </div> </div> </div> </body></html>

**Comment by bugmailer** [comment]
<html><head></head><body><div class="msg"> <div style="font-size:16px;border:1px solid #e0e0e0;max-width:800px;font-family:roboto,sans-serif;font-weight:400"> <div style="padding:20px 0px 20px 0px;text-align:center;background-color:#ffffff"><img src="https://i.stack.imgur.com/U2JVG.png" style="width:145px;min-height:40px"></div> <div style="padding:24px 24px 24px 24px;background-color:#F44336;font-family:roboto,sans-serif;font-weight:400"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div style="font-size:14px;line-height:16px;color:#fff">BugMailer Example</div> <div style="font-size:20px;line-height:24px;color:#ffffff">New issue found in com.theah64.bugmailerexample</div> </td> <td> <div style="text-align:right"><img src="https://ci6.googleusercontent.com/proxy/Cvj52vFVxSfNWI4XcQgZJvyDSATy77fAyZvSRAMKVOONvK0uQn8NBMx1LyeaDGUkZ7c8xyQ-UiwGXlRWUvEpiia0Euc3wL-kBn8aWPjlGZmGgxBZpTyJRZgJuD9RVkPun0e9m8odWw=s0-d-e1-ft#https://www.gstatic.com/images/icons/material/system/2x/bug_report_white_24dp.png" style="min-height:24px;width:24px"></div> </td> </tr> </tbody> </table> </div> <div style="font-family:roboto,sans-serif;font-weight:400"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Fatal Error</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div><b><span style='color:#F44336;'>java.lang.IllegalArgumentException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:25)</span></b></div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">App Version Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>1.0</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">App Version Code</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>1</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">File Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>MainActivity.java</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">API Level</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>23</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Time of Occurrence</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>Thu Feb 08 20:53:40 GMT+05:30 2018</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Device</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>generic_x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Model</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>Android SDK built for x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Product</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>sdk_google_phone_x86_64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Exception Message</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>java.lang.IllegalArgumentException: Test exception<br><span style='color:#F44336;'><b>	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:25)<b></span><br>	at android.view.View.performClick(View.java:5198)<br>	at android.view.View$PerformClick.run(View.java:21147)<br>	at android.os.Handler.handleCallback(Handler.java:739)<br>	at android.os.Handler.dispatchMessage(Handler.java:95)<br>	at android.os.Looper.loop(Looper.java:148)<br>	at android.app.ActivityThread.main(ActivityThread.java:5417)<br>	at java.lang.reflect.Method.invoke(Native Method)<br>	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)<br>	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)<br></div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Name</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>theapache64</div> </td> </tr> </tbody> </table> </div> </div><div style="padding:22px 24px 0px 0px;font-family:roboto,sans-serif;font-weight:400"> <div style="font-size:14px;line-height:20px;font-family:roboto,sans-serif;font-weight:400;color:#757575;padding:0px 0px 0px 24px">Age</div> <div style="padding:0px 0px 0px 24px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400;font-size:14px" cellpadding="0" cellspacing="0"> <tbody> <tr> <td> <div>20</div> </td> </tr> </tbody> </table> </div> </div><div style="background-color:#ffffff;margin:0px 0px 0px 0px;font-size:14px;font-family:roboto,sans-serif;font-weight:400"> <div style="padding-left:20px;font-size:14px;line-height:16px;padding-top:12px;padding-bottom:34px;padding-top:34px;text-align:right;font-family:roboto,sans-serif;font-weight:500"> <a href="http://google.com/search?q=java.lang.IllegalArgumentException Test exception at .MainActivity$1.onClick(MainActivity.java25)" style="text-decoration:none;margin-right:24px;padding:12px 12px 12px 12px;border:0;color:#F44336;background-color:#ffffff;font-family:roboto,sans-serif;font-weight:500;border-radius:2px" target="_blank" rel="noreferrer" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://console.firebase.google.com/project/anona-705d7/monitoring/app/android:com.cybaze.goodbuy/cluster/7846c195?utm_source%3Dalerts%26utm_medium%3Demail%26utm_campaign%3Dcrash%26utm_content%3Dcluster&amp;source=gmail&amp;ust=1504955366065000&amp;usg=AFQjCNHDa_-uwZO9NB_x2q7mwXfkTP2EYw">SEARCH WITH GOOGLE</a></div> </div> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> <hr style="display:block;border:0;border-top:1px solid #e0e0e0;margin:0px 24px 0px 24px"> </div> <div style="background-color:#343434;padding:23px 24px 23px 24px;min-height:42px"> <table style="width:100%;font-family:roboto,sans-serif;font-weight:400" cellpadding="0" cellspacing="0"> <tbody> <tr> <td style="text-align:right;padding:0"> <div style="line-height:14px;font-size:10px;color:#fff">BugMailer<br><a style="color:#fff" href="mailto:theapache64@gmail.com"> theapache64@gmail.com </a><br><a style="color:#fff" href="https://github.com/theapache64/BugMailer">A Github opensource project</a><br></div> </td> </tr> </tbody> </table> </div> </div> </div> </body></html>
