### ISSUE TITLE
java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27):1

### ISSUE THREAD

**Issue by bugmailer** [theapache64/lab#21]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Fri Feb 09 10:56:28 GMT+05:30 2018

**Device**
generic_x86_64

**Model**
Android SDK built for x86_64

**Product**
sdk_google_phone_x86_64

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Name**
theapache64

**Age**
20

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Fri Feb 09 10:56:53 GMT+05:30 2018

**Device**
generic_x86_64

**Model**
Android SDK built for x86_64

**Product**
sdk_google_phone_x86_64

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Name**
theapache64

**Age**
20

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Fri Feb 09 12:06:38 GMT+05:30 2018

**Device**
CP8676_I02

**Model**
CP8676_I02

**Product**
CP8676_I02

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5333)
	at android.view.View$PerformClick.run(View.java:21792)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:861)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

**Name**
theapache64

**Age**
20

**Comment by theapache64** [comment]
dfhdfgh

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Fri Feb 09 16:07:47 GMT+05:30 2018

**Device**
CP8676_I02

**Model**
CP8676_I02

**Product**
CP8676_I02

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5333)
	at android.view.View$PerformClick.run(View.java:21792)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:861)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

**Name**
theapache64

**Age**
20

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Sun Feb 11 20:01:43 GMT+05:30 2018

**Device**
CP8676_I02

**Model**
CP8676_I02

**Product**
CP8676_I02

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5333)
	at android.view.View$PerformClick.run(View.java:21792)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:861)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

**Name**
theapache64

**Age**
20

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)</span>

**App Version Name**
1.0

**App Version Code**
1

**File Name**
MainActivity.java

**API Level**
23

**Time of Occurrence**
Fri Aug 03 11:56:47 GMT+05:30 2018

**Device**
generic_x86_64

**Model**
Android SDK built for x86_64

**Product**
sdk_google_phone_x86_64

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$1.onClick(MainActivity.java:27)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Name**
theapache64

**Age**
20
