### ISSUE TITLE
java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$onCreate$1.onClick(MainActivity.kt:24):30201

### ISSUE THREAD

**Issue by bugmailer** [theapache64/lab#26]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$onCreate$1.onClick(MainActivity.kt:24)</span>

**App Version Name**
3.0.2-alpha01-example

**App Version Code**
30201

**File Name**
MainActivity.kt

**API Level**
24

**Time of Occurrence**
Wed Nov 06 14:29:04 GMT+05:30 2019

**Device**
clark_ds

**Model**
XT1572

**Product**
clark_retasia_ds

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$onCreate$1.onClick(MainActivity.kt:24)
	at android.view.View.performClick(View.java:5612)
	at android.view.View$PerformClick.run(View.java:22288)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Name**
theapache64

**Age**
20

**Comment by bugmailer** [comment]
**Fatal Error**
<span style='color:#THEMECOLOR;'>java.io.IOException: Test exception at com.theah64.bugmailerexample.MainActivity$onCreate$1.onClick(MainActivity.kt:24)</span>

**App Version Name**
3.0.2-alpha01-example

**App Version Code**
30201

**File Name**
MainActivity.kt

**API Level**
24

**Time of Occurrence**
Wed Nov 06 14:29:40 GMT+05:30 2019

**Device**
clark_ds

**Model**
XT1572

**Product**
clark_retasia_ds

**Exception Message**
```java
java.io.IOException: Test exception
	at com.theah64.bugmailerexample.MainActivity$onCreate$1.onClick(MainActivity.kt:24)
	at android.view.View.performClick(View.java:5612)
	at android.view.View$PerformClick.run(View.java:22288)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Name**
theapache64

**Age**
20
